/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { APP_VERSION } from "./constants";
import { resolveSlideDuration } from "./cardFormat";
import type { BackgroundMode, ExportManifest, ExportMode, ManifestSlideEntry, PhotoAsset, SlideshowPreset } from "./types";

function buildSequence(photos: PhotoAsset[], preset: SlideshowPreset): ManifestSlideEntry[] {
  return photos
    .filter((p) => p.status === "ready")
    .map((p, index) => ({
      index: index + 1,
      filename: p.filename,
      frameMode: p.frameMode && p.frameMode !== "default" ? p.frameMode : undefined,
      aspectRatio: p.aspectRatio && p.aspectRatio !== "16:9" ? p.aspectRatio : undefined,
      slideDurationSeconds:
        p.slideDurationSeconds !== undefined && p.slideDurationSeconds !== preset.slideDurationSeconds
          ? resolveSlideDuration(p, preset.slideDurationSeconds)
          : undefined,
    }));
}

export function buildManifest(params: {
  inputFolder: string;
  outputFolder: string;
  photos: PhotoAsset[];
  readyCount: number;
  preset: SlideshowPreset;
  outputFiles: string[];
  exportMode: ExportMode;
  backgroundMode: BackgroundMode;
  musicTrack?: string;
  usbFormat?: string;
}): ExportManifest {
  return {
    appVersion: APP_VERSION,
    createdAt: new Date().toISOString(),
    inputFolder: params.inputFolder,
    outputFolder: params.outputFolder,
    totalFound: params.photos.length,
    totalExported: params.readyCount,
    skipped: {
      duplicates: params.photos.filter((p) => p.status === "duplicate").length,
      unsupported: params.photos.filter((p) => p.status === "unsupported").length,
      errors: params.photos.filter((p) => p.status === "error").length,
    },
    preset: params.preset,
    outputFiles: params.outputFiles,
    usbFormat: params.usbFormat,
    exportMode: params.exportMode,
    backgroundMode: params.backgroundMode,
    musicTrack: params.musicTrack,
    sequence: buildSequence(params.photos, params.preset),
  };
}

export function buildReadmeTvGuide(params: {
  albumName: string;
  preset: SlideshowPreset;
  exportMode: ExportMode;
  outputFolder: string;
}): string {
  const { albumName, preset, exportMode, outputFolder } = params;
  return `===========================================================
    SAMSUNG SMART TV USB SLIDESHOW GUIDE
===========================================================

Album: ${albumName}
Output: ${outputFolder}
Generated by Slideshow Forge v${APP_VERSION}

TV PLAYBACK:
1. Copy the 'Samsung_Slideshows' folder to the root of your USB drive (exFAT recommended).
2. Plug USB into Samsung TV USB port (avoid hubs on older models).
3. Source → USB → open album folder.
${exportMode === "mp4" || exportMode === "both" ? "4. Play Samsung_Slideshow_Video.mp4 for one-click playback." : ""}
${exportMode === "folder" || exportMode === "both" ? "4. Open numbered JPEGs for native TV slideshow mode." : ""}

SPECS:
- Resolution: ${preset.width}x${preset.height}
- Default slide duration: ${preset.slideDurationSeconds}s (MP4 uses per-photo overrides from manifest sequence when set)
- JPEG folder: Samsung TV uses its own slideshow timing — per-card seconds apply to MP4 only
- Transitions: ${preset.transition === "crossfade" ? "crossfade (inter-slide blend, MP4)" : preset.transition} (MP4 only; folder export is instant cuts)
- Video: H.264 High L4.1, yuv420p, ${preset.fps}fps
`;
}
